on:
  release:
    types: [published]

name: tag
permissions:
    contents: write
    id-token: write
jobs:
  publish-rke2-upgrade:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Change Tag
      run: |
        echo "{GIT_TAG}=$(echo "${{ github.ref_name }}" | sed -e 's/+/-/g')}" >> "$GITHUB_ENV"

    # - name: "Read secrets"
    #   uses: rancher-eio/read-vault-secrets@main
    #   with:
    #     secrets: |
    #       secret/data/github/repo/${{ github.repository }}/dockerhub/${{ github.repository_owner }}/credentials username | DOCKER_USERNAME ;
    #       secret/data/github/repo/${{ github.repository }}/dockerhub/${{ github.repository_owner }}/credentials password | DOCKER_PASSWORD ;
    
    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build container image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: husseingalal/rke2-upgrade:${{ env.GIT_TAG }}
        file: package/Dockerfile
        platforms: linux/amd64
        build-args:
        - TAG=${{ github.ref_name }}
        - ARCH=amd64